# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 04:13
from __future__ import unicode_literals

import db.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLigand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'BaseLigand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ChemicalCompound',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('nick', models.CharField(blank=True, max_length=45)),
                ('formula', models.CharField(blank=True, max_length=45)),
                ('synthesis', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('mass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'db_table': 'ChemicalCompound',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'DataType',
            },
        ),
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'FunctionalGroup',
            },
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('nick', models.CharField(blank=True, max_length=45)),
                ('formula', models.CharField(blank=True, max_length=45)),
                ('synthesis', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('mass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('connections', models.PositiveIntegerField(blank=True, null=True)),
                ('chirality', enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True)),
                ('base_ligand', models.ForeignKey(blank=True, db_column='base_ligand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.BaseLigand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.Category')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.FunctionalGroup')),
            ],
            options={
                'db_table': 'Ligand',
            },
        ),
        migrations.CreateModel(
            name='Mof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('nick', models.CharField(blank=True, max_length=45)),
                ('formula', models.CharField(blank=True, max_length=45)),
                ('synthesis', models.TextField(blank=True)),
                ('analysis', models.TextField(blank=True)),
                ('mass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('topology', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Mof',
            },
        ),
        migrations.CreateModel(
            name='MofLigand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Ligand')),
                ('mof', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Mof')),
            ],
            options={
                'db_table': 'Mof_Ligand',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Reaction',
            },
        ),
        migrations.CreateModel(
            name='ReactionCatalystCC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chirality', enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True)),
                ('rate_constant', models.FloatField(blank=True, null=True)),
                ('conversion', models.FloatField(blank=True, null=True)),
                ('ee', models.FloatField(blank=True, null=True)),
                ('de', models.FloatField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction')),
            ],
            options={
                'db_table': 'Reaction_Catalyst_CC',
            },
        ),
        migrations.CreateModel(
            name='ReactionCatalystLigand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chirality', enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True)),
                ('rate_constant', models.FloatField(blank=True, null=True)),
                ('conversion', models.FloatField(blank=True, null=True)),
                ('ee', models.FloatField(blank=True, null=True)),
                ('de', models.FloatField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Ligand')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction')),
            ],
            options={
                'db_table': 'Reaction_Catalyst_Ligand',
            },
        ),
        migrations.CreateModel(
            name='ReactionCatalystMof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chirality', enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True)),
                ('rate_constant', models.FloatField(blank=True, null=True)),
                ('conversion', models.FloatField(blank=True, null=True)),
                ('ee', models.FloatField(blank=True, null=True)),
                ('de', models.FloatField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Mof')),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction')),
            ],
            options={
                'db_table': 'Reaction_Catalyst_Mof',
            },
        ),
        migrations.CreateModel(
            name='ReactionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_file', models.FileField(upload_to='reaction_data/')),
                ('data_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.DataType')),
                ('reaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Reaction')),
            ],
            options={
                'db_table': 'ReactionData',
            },
        ),
        migrations.CreateModel(
            name='ReactionProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction')),
            ],
            options={
                'db_table': 'Reaction_Product',
            },
        ),
        migrations.CreateModel(
            name='ReactionReactant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction')),
            ],
            options={
                'db_table': 'Reaction_Reactant',
            },
        ),
        migrations.CreateModel(
            name='VisualizationCC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemdraw', models.FileField(upload_to='visualization/cc/')),
                ('chemical_compound', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualization', to='db.ChemicalCompound')),
            ],
            options={
                'db_table': 'VisualizationCC',
            },
        ),
        migrations.CreateModel(
            name='VisualizationLigand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemdraw', models.FileField(upload_to='visualization/ligand/')),
                ('ligand', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualization', to='db.Ligand')),
            ],
            options={
                'db_table': 'VisualizationLigand',
            },
        ),
        migrations.CreateModel(
            name='VisualizationMof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cif', models.FileField(db_column='CIF', upload_to='visualization/mof/cif/')),
                ('mof', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualization', to='db.Mof')),
            ],
            options={
                'db_table': 'VisualizationMof',
            },
        ),
        migrations.CreateModel(
            name='VisualizationReaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chemdraw', models.FileField(upload_to='visualization/reaction/')),
                ('reaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visualization', to='db.Reaction')),
            ],
            options={
                'db_table': 'VisualizationReaction',
            },
        ),
        migrations.AddField(
            model_name='reaction',
            name='catalysts_cc',
            field=models.ManyToManyField(blank=True, related_name='reaction_catalysts', through='db.ReactionCatalystCC', to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='catalysts_ligand',
            field=models.ManyToManyField(blank=True, related_name='reaction_catalysts', through='db.ReactionCatalystLigand', to='db.Ligand'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='catalysts_mof',
            field=models.ManyToManyField(blank=True, related_name='reaction_catalysts', through='db.ReactionCatalystMof', to='db.Mof'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='reaction_products', through='db.ReactionProduct', to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='reactants',
            field=models.ManyToManyField(blank=True, related_name='reaction_reactants', through='db.ReactionReactant', to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='mof',
            name='ligands',
            field=models.ManyToManyField(related_name='mofs', through='db.MofLigand', to='db.Ligand'),
        ),
    ]
