# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionCatalystsLigand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reaction_Catalysts_Ligand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseLigand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('base_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'BaseLigand',
            },
        ),
        migrations.CreateModel(
            name='CatalystData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('functional_group_id', models.IntegerField(blank=True, null=True)),
                ('chirality', models.CharField(blank=True, max_length=4, null=True)),
                ('rate_constant', models.FloatField(blank=True, null=True)),
                ('conversion', models.FloatField(blank=True, null=True)),
                ('ee_field', models.FloatField(blank=True, null=True)),
                ('de_field', models.FloatField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CatalystData',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='ChemicalCompound',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick', models.CharField(blank=True, max_length=45, null=True)),
                ('formula', models.CharField(blank=True, max_length=45, null=True)),
                ('synthesis', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ChemicalCompound',
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'DataType',
            },
        ),
        migrations.CreateModel(
            name='FunctionalGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chirality', models.CharField(blank=True, max_length=4, null=True)),
                ('rate_constant', models.FloatField(blank=True, null=True)),
                ('conversion', models.FloatField(blank=True, null=True)),
                ('ee', models.FloatField(blank=True, null=True)),
                ('de', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('functional_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup')),
            ],
            options={
                'db_table': 'FunctionalGroup',
            },
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick', models.CharField(blank=True, max_length=45, null=True)),
                ('formula', models.CharField(blank=True, max_length=45, null=True)),
                ('synthesis', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('connections', models.IntegerField(blank=True, null=True)),
                ('chirality', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'Ligand',
            },
        ),
        migrations.CreateModel(
            name='Mof',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick', models.CharField(blank=True, max_length=45, null=True)),
                ('formula', models.CharField(blank=True, max_length=45, null=True)),
                ('synthesis', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True)),
                ('topology', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mof',
            },
        ),
        migrations.CreateModel(
            name='MofLigands',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Mof_Ligands',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reaction',
            },
        ),
        migrations.CreateModel(
            name='ReactionCatalystsCC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reaction_Catalysts_CC',
            },
        ),
        migrations.CreateModel(
            name='ReactionCatalystsMof',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('catalyst_data', models.ForeignKey(db_column='catalyst_data', on_delete=django.db.models.deletion.DO_NOTHING, to='db.CatalystData')),
            ],
            options={
                'db_table': 'Reaction_Catalysts_Mof',
            },
        ),
        migrations.CreateModel(
            name='ReactionProducts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Reaction_Products',
            },
        ),
        migrations.CreateModel(
            name='ReactionReactants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Reaction_Reactants',
            },
        ),
        migrations.CreateModel(
            name='ReactionData',
            fields=[
                ('id_reaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.Reaction')),
                ('data', models.TextField()),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.DataType')),
            ],
            options={
                'db_table': 'ReactionData',
            },
        ),
        migrations.CreateModel(
            name='VisualizationCC',
            fields=[
                ('id_chemical_compound', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.ChemicalCompound')),
                ('chemdraw', models.TextField()),
            ],
            options={
                'db_table': 'VisualizationCC',
            },
        ),
        migrations.CreateModel(
            name='VisualizationLigand',
            fields=[
                ('id_ligand', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.Ligand')),
                ('chemdraw', models.TextField()),
            ],
            options={
                'db_table': 'VisualizationLigand',
            },
        ),
        migrations.CreateModel(
            name='VisualizationMof',
            fields=[
                ('id_mof', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.Mof')),
                ('cif', models.TextField(db_column='CIF')),
            ],
            options={
                'db_table': 'VisualizationMof',
            },
        ),
        migrations.CreateModel(
            name='VisualizationReaction',
            fields=[
                ('id_reaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.Reaction')),
                ('chemdraw', models.TextField()),
            ],
            options={
                'db_table': 'VisualizationReaction',
            },
        ),
        migrations.AddField(
            model_name='reactionreactants',
            name='reactant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='reactionreactants',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AddField(
            model_name='reactionproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='reactionproducts',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AddField(
            model_name='reactioncatalystsmof',
            name='catalyst_mof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Mof'),
        ),
        migrations.AddField(
            model_name='reactioncatalystsmof',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AddField(
            model_name='reactioncatalystscc',
            name='catalyst_cc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
        migrations.AddField(
            model_name='reactioncatalystscc',
            name='catalyst_data',
            field=models.ForeignKey(db_column='catalyst_data', on_delete=django.db.models.deletion.DO_NOTHING, to='db.CatalystData'),
        ),
        migrations.AddField(
            model_name='reactioncatalystscc',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AddField(
            model_name='mofligands',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Ligand'),
        ),
        migrations.AddField(
            model_name='mofligands',
            name='mof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Mof'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='base_ligand',
            field=models.ForeignKey(blank=True, db_column='base_ligand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.BaseLigand'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Category'),
        ),
        migrations.AddField(
            model_name='ligand',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup'),
        ),
        migrations.AddField(
            model_name='baseligand',
            name='base_ligand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Ligand'),
        ),
    ]
