# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('component_id', models.PositiveIntegerField(null=True, verbose_name='related object')),
                ('component_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('experimental_data_id', models.ForeignKey(blank=True, db_column='ExperimentalData', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_cc', to='db.ExperimentalData')),
            ],
            options={
                'verbose_name': 'Reaction Component',
                'verbose_name_plural': 'Reaction Components',
                'db_table': 'Reaction_Component',
            },
        ),
        migrations.RemoveField(
            model_name='reactioncatalystcc',
            name='catalyst_cc_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystcc',
            name='experimental_data_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystcc',
            name='reaction_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystligand',
            name='catalyst_ligand_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystligand',
            name='experimental_data_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystligand',
            name='reaction_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystmof',
            name='catalyst_mof_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystmof',
            name='experimental_data_id',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystmof',
            name='reaction_id',
        ),
        migrations.RemoveField(
            model_name='reactionproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='reactionproduct',
            name='reaction_id',
        ),
        migrations.RemoveField(
            model_name='reactionreactant',
            name='reactant',
        ),
        migrations.RemoveField(
            model_name='reactionreactant',
            name='reaction',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='reaction',
            name='catalysts_cc',
            field=gm2m.fields.GM2MField(blank=True, related_name='catalysts_cc', through='db.ReactionComponent', through_fields=['reaction_id', 'component', 'component_type', 'component_id']),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='catalysts_ligand',
            field=gm2m.fields.GM2MField(blank=True, related_name='catalysts_ligands', through='db.ReactionComponent', through_fields=['reaction_id', 'component', 'component_type', 'component_id']),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='catalysts_mof',
            field=gm2m.fields.GM2MField(blank=True, related_name='catalysts_mofs', through='db.ReactionComponent', through_fields=['reaction_id', 'component', 'component_type', 'component_id']),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='products',
            field=gm2m.fields.GM2MField(blank=True, related_name='products', through='db.ReactionComponent', through_fields=['reaction_id', 'component', 'component_type', 'component_id']),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reactants',
            field=gm2m.fields.GM2MField(blank=True, related_name='reactants', through='db.ReactionComponent', through_fields=['reaction_id', 'component', 'component_type', 'component_id']),
        ),
        migrations.DeleteModel(
            name='ReactionCatalystCC',
        ),
        migrations.DeleteModel(
            name='ReactionCatalystLigand',
        ),
        migrations.DeleteModel(
            name='ReactionCatalystMof',
        ),
        migrations.DeleteModel(
            name='ReactionProduct',
        ),
        migrations.DeleteModel(
            name='ReactionReactant',
        ),
        migrations.AddField(
            model_name='reactioncomponent',
            name='reaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
    ]
