# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-29 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalystdata',
            name='functional_group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.FunctionalGroup'),
        ),
    ]
