# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 00:21
from __future__ import unicode_literals

import db.models
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactioncatalystcc',
            name='chirality',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystcc',
            name='functional_group',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystligand',
            name='chirality',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystligand',
            name='functional_group',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystmof',
            name='chirality',
        ),
        migrations.RemoveField(
            model_name='reactioncatalystmof',
            name='functional_group',
        ),
        migrations.AddField(
            model_name='chemicalcompound',
            name='chirality',
            field=enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='chemicalcompound',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chemicalcompound', to='db.FunctionalGroup'),
        ),
        migrations.AlterField(
            model_name='chemicalcompound',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chemicalcompound',
            name='nick',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='nick',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mof',
            name='formula',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mof',
            name='nick',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mof',
            name='topology',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
