# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170828_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionalgroup',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='chirality',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='de',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='ee',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='functional_group',
        ),
        migrations.RemoveField(
            model_name='functionalgroup',
            name='rate_constant',
        ),
        migrations.AddField(
            model_name='functionalgroup',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
