# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20171010_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachment/')),
                ('description_short', models.CharField(blank=True, max_length=200, verbose_name='Short Description')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentChemicalCompound',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Attachment')),
                ('chemicalcompound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.ChemicalCompound')),
            ],
            bases=('db.attachment',),
        ),
        migrations.CreateModel(
            name='AttachmentLigand',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Attachment')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.Ligand')),
            ],
            bases=('db.attachment',),
        ),
        migrations.CreateModel(
            name='AttachmentMof',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Attachment')),
                ('mof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.Mof')),
            ],
            bases=('db.attachment',),
        ),
        migrations.CreateModel(
            name='AttachmentReaction',
            fields=[
                ('attachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Attachment')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='db.Reaction')),
            ],
            bases=('db.attachment',),
        ),
    ]
