# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170925_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigandCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'LigandCategory',
                'verbose_name_plural': 'LigandCategories',
            },
        ),
        migrations.CreateModel(
            name='ReactionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'ReactionCategory',
                'verbose_name_plural': 'ReactionCategories',
            },
        ),
        migrations.AlterField(
            model_name='ligand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.LigandCategory'),
        ),
        migrations.AlterField(
            model_name='reactiondata',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='reaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reactions', to='db.ReactionCategory'),
        ),
    ]
