# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20170921_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactioncatalystcc',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='reactioncatalystcc',
            old_name='functional_group_id',
            new_name='functional_group',
        ),
        migrations.RenameField(
            model_name='reactioncatalystcc',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='reactioncatalystligand',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='reactioncatalystligand',
            old_name='functional_group_id',
            new_name='functional_group',
        ),
        migrations.RenameField(
            model_name='reactioncatalystligand',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='reactioncatalystmof',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='reactioncatalystmof',
            old_name='functional_group_id',
            new_name='functional_group',
        ),
        migrations.RenameField(
            model_name='reactioncatalystmof',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='reactiondata',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='reactionproduct',
            old_name='component_id',
            new_name='component',
        ),
        migrations.RenameField(
            model_name='reactionproduct',
            old_name='reaction_id',
            new_name='reaction',
        ),
        migrations.RenameField(
            model_name='reactionreactant',
            old_name='component_id',
            new_name='component',
        ),
    ]
