# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_attachment_attachmentchemicalcompound_attachmentligand_attachmentmof_attachmentreaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='structure_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='visualizationcc',
            name='chemical_compound',
        ),
        migrations.RemoveField(
            model_name='visualizationligand',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='visualizationmof',
            name='mof',
        ),
        migrations.RemoveField(
            model_name='visualizationreaction',
            name='reaction',
        ),
        migrations.CreateModel(
            name='StructureChemicalCompound',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Structure')),
                ('chemicalcompound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='db.ChemicalCompound')),
            ],
            bases=('db.structure',),
        ),
        migrations.CreateModel(
            name='StructureLigand',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Structure')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='db.Ligand')),
            ],
            bases=('db.structure',),
        ),
        migrations.CreateModel(
            name='StructureReaction',
            fields=[
                ('structure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.Structure')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='db.Reaction')),
            ],
            bases=('db.structure',),
        ),
        migrations.DeleteModel(
            name='VisualizationCC',
        ),
        migrations.DeleteModel(
            name='VisualizationLigand',
        ),
        migrations.DeleteModel(
            name='VisualizationMof',
        ),
        migrations.DeleteModel(
            name='VisualizationReaction',
        ),
    ]
