# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20170921_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='type',
            new_name='name',
        ),
    ]
