# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 05:43
from __future__ import unicode_literals

import db.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20170828_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalystdata',
            name='chirality',
            field=enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='chirality',
            field=enumfields.fields.EnumField(blank=True, enum=db.models.Chirality, max_length=5, null=True),
        ),
    ]
