# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20171116_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='attachment',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
