# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20170828_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionCatalystLigand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Reaction_Catalyst_Ligand',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='MofLigands',
            new_name='MofLigand',
        ),
        migrations.RenameModel(
            old_name='ReactionCatalystsCC',
            new_name='ReactionCatalystCC',
        ),
        migrations.RenameModel(
            old_name='ReactionCatalystsMof',
            new_name='ReactionCatalystMof',
        ),
        migrations.RenameModel(
            old_name='ReactionProducts',
            new_name='ReactionProduct',
        ),
        migrations.RenameModel(
            old_name='ReactionReactants',
            new_name='ReactionReactant',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='mofligand',
            table='Mof_Ligand',
        ),
        migrations.AlterModelTable(
            name='reactioncatalystcc',
            table='Reaction_Catalyst_CC',
        ),
        migrations.AlterModelTable(
            name='reactioncatalystmof',
            table='Reaction_Catalyst_Mof',
        ),
        migrations.AlterModelTable(
            name='reactionproduct',
            table='Reaction_Product',
        ),
        migrations.AlterModelTable(
            name='reactionreactant',
            table='Reaction_Reactant',
        ),
    ]
