# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20170921_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='base_ligand',
            field=models.ForeignKey(blank=True, db_column='base_ligand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.BaseLigand'),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.Category'),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='functional_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ligands', to='db.FunctionalGroup'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystcc',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystcc',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystligand',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Ligand'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystligand',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystmof',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Mof'),
        ),
        migrations.AlterField(
            model_name='reactioncatalystmof',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.Reaction'),
        ),
        migrations.AlterField(
            model_name='reactionproduct',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
        migrations.AlterField(
            model_name='reactionreactant',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ChemicalCompound'),
        ),
    ]
