# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20171129_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mof',
            options={'verbose_name': 'MOF', 'verbose_name_plural': 'MOFs'},
        ),
    ]
